### ISSUE TITLE
Support FVM 3.0

### ISSUE THREAD

**Issue by chillbrodev** [infinum/Install-Flutter-Version-Manager-Bitrise#3]
Hello, I wanted to bring this to your attention that FVM is making updates to how it manages Flutter. https://github.com/leoafarias/fvm/blob/main/CHANGELOG.md#300-beta5

**Comment by chillbrodev** [comment]
@itsJoKr Are there plans to support the new FVM?

**Comment by royd** [comment]
Until https://github.com/bitrise-io/bitrise-steplib/pull/4119 is merged, you can use the updated step by replacing this in your bitrise.yaml
`- install-flutter-version-manager@1: {}`
with this
`- git::https://github.com/infinum/Install-Flutter-Version-Manager-Bitrise@2.0.0: {}`

Note:
You will also need to use `$FVM_FLUTTER_VERSION` as your version in the Flutter Install step.

**Comment by chillbrodev** [comment]
@royd Thanks that sounds good. It turns out that the current step is working without issue, likely due to FVM's legacy support.

**Comment by zenled** [comment]
Closing, the new version of this step has been published (Extract FVM Flutter version `v2.0.0`).
This step now parses the Flutter version from the `.fvmrc` file. The parsed version can then be passed to the Flutter Install step (`$FVM_FLUTTER_VERSION`).
